language: python

python:
  - "2.6"
  - "2.7"

virtualenv:
  system_site_packages: true

sudo: required

before_install:
  - sudo export TZ='Asia/Shanghai'
  - sed -i "s/email_account/$smtp_user/g" ./test/conf/email_config.ini
  - sed -i "s/email_passwd/$smtp_pswd/g" ./test/conf/email_config.ini

install:
  - sudo pip install -r requirements.txt
  - python setup.py build
  - python setup.py install

script:
  - python -u ./test/suites_start.py